name: Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/publish.yml'
      - 'support/docs/mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest